# Generated by Django 3.0.5 on 2020-05-17 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tracker', '0003_auto_20200517_1037'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('affiliate_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.AffiliateURL')),
            ],
        ),
    ]
