# Generated by Django 3.0.5 on 2020-05-17 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clickevent',
            name='remote_add',
            field=models.GenericIPAddressField(default='127.0.0.1'),
        ),
    ]
