# Generated by Django 3.0.5 on 2020-05-16 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliateurl',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='affiliateurl',
            name='shortcode',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
