# Generated by Django 3.0.5 on 2020-05-17 10:37

from django.db import migrations, models
import tracker.validators


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20200516_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliateurl',
            name='url',
            field=models.CharField(max_length=220, validators=[tracker.validators.validate_url]),
        ),
    ]
