# Generated by Django 3.0.5 on 2020-05-17 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20200517_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliateurl',
            name='sessionid',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
